name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Lint
        run: npm run lint --if-present
        continue-on-error: true

      - name: Build
        run: npm run build --if-present
        continue-on-error: true

      - name: Test
        run: npm test --if-present -- --reporter=verbose --no-coverage --passWithNoTests

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Lint
        run: npm run lint --if-present
        continue-on-error: true

      - name: Build
        run: npm run build
        continue-on-error: true

      - name: Test
        run: npm run test:run --if-present
        env:
          CI: true

# Removed duplicate workflow definition below to ensure jobs run correctly