name: Lighthouse CI

on:
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Start preview server
        working-directory: frontend
        run: |
          npx serve -s dist -l 4173 &
          sleep 3

      - name: Run Lighthouse CI
        run: |
          npx @lhci/cli@0.13.x autorun --collect.url=http://localhost:4173 --upload.target=temporary-public-storage


